# Generated by Django 4.1.3 on 2023-06-26 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphs', '0003_poll_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
