# Generated by Django 4.1.3 on 2023-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0012_alter_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default='64215608', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
