# Generated by Django 4.1.3 on 2023-06-25 15:05

from django.db import migrations, models
import mainPoll.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.IntegerField(default=mainPoll.models.generate_random_code,
                                      editable=False, primary_key=True, serialize=False),
        ),
    ]
