# Generated by Django 4.2.1 on 2023-06-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPoll', '0005_remove_poll_voters_pollchoices_voters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.IntegerField(
                default='poll-22312638', editable=False, primary_key=True, serialize=False),
        ),
    ]
