# Generated by Django 4.2.1 on 2023-06-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPoll', '0008_remove_poll_options_pollchoices_poll_rs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(default='poll-60531051', editable=False,
                                   max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pollchoices',
            name='poll_rs',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mainPoll.poll'),
        ),
    ]
