# Generated by Django 4.1.3 on 2023-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPoll', '0013_alter_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.CharField(
                editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
