# Generated by Django 4.1.3 on 2023-07-19 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainPoll', '0014_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
